### ISSUE TITLE
Deleting a folder after zipping

### ISSUE THREAD

**Issue by clifgriffin** [yyhappynice/webpack-zip-plugin#2]
This is might be something worth adding to the documentation, because it's an easy solution to a pretty obnoxious problem.

Most cleanup plugins run exclusively before building is started. And webpack-zip-plugin runs after building is done. So there isn't really a great place to jump in and delete the folder you zipped. (Believe me, I've tried)

However, I found a clever little workaround. It looks like this:
```js
module.exports.plugins.push(
        new WebpackZipPlugin({
            initialFile: 'foo && rm -rf ' + buildDir,
            endPath: './dist',
            zipName: 'foo-' + version + '.zip'
        })
    );
```

Because of how the commands are executed, you can pipe another command at the end of initialFile. This worked perfectly after an hour of banging my head against a wall with other modules.

**Comment by yyhappynice** [comment]
Maybe I need to add options  `frontShell` and `behindShell` ？

**Comment by yyhappynice** [comment]
Hi~ @clifgriffin I added the configuration you can use `frontShell ` and `behindShell ` ，arrying out commands before and after zip.  update@0.1.3

**Comment by yyhappynice** [comment]
Hi~ @clifgriffin I added the configuration you can use `frontShell` and `behindShell` ，arrying out commands when before and after zip. update@0.1.3～ 😊

**Comment by clifgriffin** [comment]
Awesome! I know this is going to help a lot of people. 👍🏻
